/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthKakaoRouteImport } from './routes/api/auth/kakao'
import { Route as ApiAuthKakaoCallbackRouteImport } from './routes/api/auth/kakao.callback'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthKakaoRoute = ApiAuthKakaoRouteImport.update({
  id: '/api/auth/kakao',
  path: '/api/auth/kakao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthKakaoCallbackRoute = ApiAuthKakaoCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthKakaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/api/auth/kakao': typeof ApiAuthKakaoRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/kakao/callback': typeof ApiAuthKakaoCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/api/auth/kakao': typeof ApiAuthKakaoRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/kakao/callback': typeof ApiAuthKakaoCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/api/auth/kakao': typeof ApiAuthKakaoRouteWithChildren
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/kakao/callback': typeof ApiAuthKakaoCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/profile'
    | '/api/auth/kakao'
    | '/api/auth/logout'
    | '/api/auth/kakao/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/profile'
    | '/api/auth/kakao'
    | '/api/auth/logout'
    | '/api/auth/kakao/callback'
  id:
    | '__root__'
    | '/'
    | '/landing'
    | '/login'
    | '/profile'
    | '/api/auth/kakao'
    | '/api/auth/logout'
    | '/api/auth/kakao/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ApiAuthKakaoRoute: typeof ApiAuthKakaoRouteWithChildren
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/kakao': {
      id: '/api/auth/kakao'
      path: '/api/auth/kakao'
      fullPath: '/api/auth/kakao'
      preLoaderRoute: typeof ApiAuthKakaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/kakao/callback': {
      id: '/api/auth/kakao/callback'
      path: '/callback'
      fullPath: '/api/auth/kakao/callback'
      preLoaderRoute: typeof ApiAuthKakaoCallbackRouteImport
      parentRoute: typeof ApiAuthKakaoRoute
    }
  }
}

interface ApiAuthKakaoRouteChildren {
  ApiAuthKakaoCallbackRoute: typeof ApiAuthKakaoCallbackRoute
}

const ApiAuthKakaoRouteChildren: ApiAuthKakaoRouteChildren = {
  ApiAuthKakaoCallbackRoute: ApiAuthKakaoCallbackRoute,
}

const ApiAuthKakaoRouteWithChildren = ApiAuthKakaoRoute._addFileChildren(
  ApiAuthKakaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ApiAuthKakaoRoute: ApiAuthKakaoRouteWithChildren,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
